# ---------- FIRST TEST (wirh baked .env) ----------
FROM python:3.11-slim AS runtime

# non-root user
RUN useradd -m appuser

# workdir
WORKDIR /app

# Leverage Docker layer caching: install deps first
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Security + perms
RUN chown -R appuser:appuser /app
USER appuser

# Flask/Gunicorn defaults
ENV PYTHONUNBUFFERED=1 \
    PORT=8080

# Expose runtime port
EXPOSE 8080

CMD ["gunicorn", "-w", "2", "-k", "gthread", "-b", "0.0.0.0:8080", "app:app"]
